"use client";
import { useState } from "react";
export default function Page() {
  const [fg, setFg] = useState("#ffffff");
  const [bg, setBg] = useState("#1e293b");
  const hexToRgb = h => { const r=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h); return r?{r:parseInt(r[1],16),g:parseInt(r[2],16),b:parseInt(r[3],16)}:null; };
  const luminance = c => { if(!c) return 0; const s=v=>{v/=255;return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4);}; return 0.2126*s(c.r)+0.7152*s(c.g)+0.0722*s(c.b); };
  const ratio = () => { const l1=luminance(hexToRgb(fg)),l2=luminance(hexToRgb(bg)); return ((Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05)).toFixed(2); };
  const r = parseFloat(ratio());
  const aa = r>=4.5, aaa = r>=7, aaLarge = r>=3;
  return (<div style={{padding:"2rem",fontFamily:"monospace",background:"#0f172a",minHeight:"100vh",color:"#e2e8f0"}}><h1 style={{color:"#38bdf8",marginBottom:"1rem"}}>Color Contrast Checker</h1><p style={{color:"#94a3b8",marginBottom:"1.5rem"}}>Check WCAG color contrast ratios for accessibility.</p><div style={{display:"flex",gap:"2rem",marginBottom:"1.5rem"}}><div><label style={{color:"#94a3b8",display:"block",marginBottom:"0.5rem"}}>Foreground</label><input type="color" value={fg} onChange={e=>setFg(e.target.value)} style={{width:"60px",height:"40px",cursor:"pointer"}}/><input value={fg} onChange={e=>setFg(e.target.value)} style={{marginLeft:"0.5rem",padding:"0.25rem",background:"#1e293b",border:"1px solid #334155",color:"#e2e8f0",borderRadius:"4px",width:"90px"}}/></div><div><label style={{color:"#94a3b8",display:"block",marginBottom:"0.5rem"}}>Background</label><input type="color" value={bg} onChange={e=>setBg(e.target.value)} style={{width:"60px",height:"40px",cursor:"pointer"}}/><input value={bg} onChange={e=>setBg(e.target.value)} style={{marginLeft:"0.5rem",padding:"0.25rem",background:"#1e293b",border:"1px solid #334155",color:"#e2e8f0",borderRadius:"4px",width:"90px"}}/></div></div><div style={{padding:"1.5rem",background:bg,borderRadius:"8px",marginBottom:"1.5rem",textAlign:"center"}}><p style={{color:fg,fontSize:"1.25rem",margin:0}}>Sample Text Preview</p><p style={{color:fg,fontSize:"0.875rem",margin:"0.5rem 0 0"}}>Small text sample for readability check</p></div><div style={{background:"#1e293b",padding:"1rem",borderRadius:"8px"}}><p style={{fontSize:"1.5rem",fontWeight:"bold",color:"#f1f5f9"}}>Ratio: {r}:1</p><div style={{display:"flex",gap:"1rem",flexWrap:"wrap"}}>{[{l:"AA Normal",p:aa},{l:"AA Large",p:aaLarge},{l:"AAA Normal",p:aaa}].map(({l,p})=><span key={l} style={{padding:"0.25rem 0.75rem",background:p?"#166534":"#7f1d1d",color:p?"#86efac":"#fca5a5",borderRadius:"4px"}}>{l}: {p?"Pass":"Fail"}</span>)}</div></div></div>);
}