"use client";
import { useState } from "react";
export default function ColorContrastChecker() {
  const [fg, setFg] = useState("#ffffff");
  const [bg, setBg] = useState("#000000");
  const hexToRgb = (hex: string) => { const r = parseInt(hex.slice(1,3),16); const g = parseInt(hex.slice(3,5),16); const b = parseInt(hex.slice(5,7),16); return [r,g,b]; };
  const luminance = (r: number, g: number, b: number) => { const [rs,gs,bs] = [r,g,b].map(c => { const s = c/255; return s <= 0.03928 ? s/12.92 : Math.pow((s+0.055)/1.055,2.4); }); return 0.2126*rs + 0.7152*gs + 0.0722*bs; };
  const contrast = () => { try { const [r1,g1,b1] = hexToRgb(fg); const [r2,g2,b2] = hexToRgb(bg); const l1 = luminance(r1,g1,b1); const l2 = luminance(r2,g2,b2); const ratio = (Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05); return ratio.toFixed(2); } catch { return "?"; } };
  const ratio = parseFloat(contrast());
  const aa = ratio >= 4.5; const aaa = ratio >= 7; const aaLarge = ratio >= 3;
  return (<div style={{padding:"2rem",fontFamily:"monospace",background:"#0f0f0f",minHeight:"100vh",color:"#e2e8f0"}}><h1 style={{fontSize:"1.5rem",marginBottom:"1rem"}}>Color Contrast Checker</h1><p style={{color:"#94a3b8",marginBottom:"1.5rem"}}>Check WCAG color contrast ratio for accessibility.</p><div style={{display:"flex",gap:"2rem",marginBottom:"1.5rem",flexWrap:"wrap"}}><div><label style={{display:"block",marginBottom:"0.5rem",color:"#94a3b8"}}>Foreground</label><input type="color" value={fg} onChange={e=>setFg(e.target.value)} style={{width:"80px",height:"40px",border:"none",borderRadius:"4px",cursor:"pointer"}} /><input value={fg} onChange={e=>setFg(e.target.value)} style={{marginLeft:"0.5rem",padding:"0.5rem",background:"#1e293b",border:"1px solid #334155",borderRadius:"4px",color:"#e2e8f0",width:"90px"}} /></div><div><label style={{display:"block",marginBottom:"0.5rem",color:"#94a3b8"}}>Background</label><input type="color" value={bg} onChange={e=>setBg(e.target.value)} style={{width:"80px",height:"40px",border:"none",borderRadius:"4px",cursor:"pointer"}} /><input value={bg} onChange={e=>setBg(e.target.value)} style={{marginLeft:"0.5rem",padding:"0.5rem",background:"#1e293b",border:"1px solid #334155",borderRadius:"4px",color:"#e2e8f0",width:"90px"}} /></div></div><div style={{background:bg,color:fg,padding:"1.5rem",borderRadius:"8px",marginBottom:"1.5rem",fontSize:"1.2rem",textAlign:"center"}}>Sample Text Preview</div><div style={{background:"#1e293b",padding:"1rem",borderRadius:"6px"}}><div style={{fontSize:"2rem",fontWeight:"bold",color: ratio >= 4.5 ? "#a3e635" : "#f87171",marginBottom:"0.5rem"}}>{contrast()}:1</div><div style={{display:"flex",gap:"1rem",flexWrap:"wrap"}}>{[{label:"AA Normal",pass:aa},{label:"AA Large",pass:aaLarge},{label:"AAA Normal",pass:aaa}].map(({label,pass})=><span key={label} style={{padding:"0.25rem 0.75rem",borderRadius:"4px",background: pass ? "#166534" : "#7f1d1d",color: pass ? "#a3e635" : "#fca5a5"}}>{pass ? "PASS" : "FAIL"} {label}</span>)}</div></div></div>);
}
