"use client";
import { useState } from "react";
export default function Page() {
  const [val, setVal] = useState("");
  const [from, setFrom] = useState("gy");
  const [to, setTo] = useState("mgy");
  const factors: Record<string,number> = {gy: 1, mgy: 1, rad: 1, sv: 1, msv: 1, rem: 1, mrem: 1};
  const result = val && factors[from] && factors[to] ? ((parseFloat(val) * factors[from]) / factors[to]).toFixed(6) : "";
  return (<div style={{padding:"2rem",maxWidth:"600px",margin:"0 auto",fontFamily:"sans-serif"}}><h1 style={{fontSize:"1.8rem",marginBottom:"0.5rem"}}>Radiation Dose Converter</h1><p style={{color:"#888",marginBottom:"1.5rem"}}>Convert between radiation dose units: gray, rad, sievert, rem, and roentgen.</p><div style={{display:"flex",gap:"1rem",flexWrap:"wrap",alignItems:"center"}}><input type="number" value={val} onChange={e=>setVal(e.target.value)} placeholder="Value" style={{padding:"0.5rem",fontSize:"1rem",borderRadius:"6px",border:"1px solid #444",background:"#1a1a1a",color:"#fff",width:"140px"}}/><select value={from} onChange={e=>setFrom(e.target.value)} style={{padding:"0.5rem",fontSize:"1rem",borderRadius:"6px",border:"1px solid #444",background:"#1a1a1a",color:"#fff"}}><option value="gy">gray (Gy)</option><option value="mgy">milligray (mGy)</option><option value="rad">rad</option><option value="sv">sievert (Sv)</option><option value="msv">millisievert (mSv)</option><option value="rem">rem</option><option value="mrem">millirem (mrem)</option></select><span>→</span><select value={to} onChange={e=>setTo(e.target.value)} style={{padding:"0.5rem",fontSize:"1rem",borderRadius:"6px",border:"1px solid #444",background:"#1a1a1a",color:"#fff"}}><option value="gy">gray (Gy)</option><option value="mgy">milligray (mGy)</option><option value="rad">rad</option><option value="sv">sievert (Sv)</option><option value="msv">millisievert (mSv)</option><option value="rem">rem</option><option value="mrem">millirem (mrem)</option></select></div>{result && <div style={{marginTop:"1.5rem",padding:"1rem",background:"#1a1a1a",borderRadius:"8px",fontSize:"1.5rem",color:"#4ade80"}}><strong>{val} {from}</strong> = <strong>{result} {to}</strong></div>}</div>);
}
